version: '3.8'
services:
  db:
    container_name: red-fox-db
    image: docker.io/mysql:8.0.28-oracle
    restart: "no"
    volumes:
      - "./db/datadir:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
