listeners:
  grpcPort: 8081
  restPort: 8080
database:
  type: Mysql
  url: "mysql://localhost:3306/red_fox"
  usernameRef:
    type: Static
    value: "root"
  passwordRef:
    type: Static
    value: "mypassword"
externalDns:
  enabled: true
  port: 9000
  syncInterval: 120s
  natIpNameTemplate: "{{ .Name }}.{{ .Namespace }}.nats.example.com"
  natIpLabelTemplate: "{{ .Name }}.{{ .Namespace }}.labels.nats.example.com"
  endpointNameTemplate: "{{ .Name }}.{{ .Namespace }}.endpoints.example.com"
  endpointLabelTemplate: "{{ .Name }}.{{ .Namespace }}.labels.endpoints.example.com"
