listeners:
  grpcPort: 8081
  restPort: 8080
database:
  type: Mysql
  url: "mysql://localhost:3306/red_fox"
  usernameRef:
    type: Static
    value: "root"
  passwordRef:
    type: Static
    value: "mypassword"
externalDns:
  enabled: true
  port: 9000
  syncInterval: 120s
  natIpDomain: srv.my-central.io
  endpointDomain: srv.my-central.io
