listeners:
  grpcPort: 8081
  restPort: 8080
database:
  type: Mysql
  url: "mysql://localhost:3306/red_fox"
  usernameRef:
    type: Static
    value: "root"
  passwordRef:
    type: Static
    value: "mypassword"
externalDns:
  enabled: true
  port: 9000
  syncInterval: 120s
  templates:
    natIpName: "{{ .Name }}.{{ .Namespace }}.nats.example.com"
    natIpLabel: "{{ .Key }}.{{ .Namespace }}.labels.nats.example.com"
    natIpLabelWithValue: "{{ .Value }}.{{ .Key }}.{{ .Namespace }}.labels.nats.example.com"
    endpointName: "{{ .Name }}.{{ .Namespace }}.endpoints.example.com"
    endpointLabel: "{{ .Key }}.{{ .Namespace }}.labels.endpoints.example.com"
    endpointLabelWithValue: "{{ .Value }}.{{ .Key }}.{{ .Namespace }}.labels.endpoints.example.com"
