listeners:
  grpcPort: 8081
  restPort: 8080
database:
  type: 1
  url: "mysql://localhost:3306/red_fox"
  usernameRef:
    type: 0
    value: "root"
  passwordRef:
    type: 0
    value: "mypassword"
